apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk045-teammate
  namespace: skala-practice
  labels:
    app: sk045-teammate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk045-teammate
  template:
    metadata:
      labels:
        app: sk045-teammate
    spec:
      containers:
        - name: sk045-teammate
          image: amdp-registry.skala-ai.com/skala25a/sk045-teammate:3.0.1-3-98ab70b917a1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: sk045-teammate-config
          env:
            - name: USER_NAME
              value: sk045
            - name: LOGGING_LEVEL_ROOT
              value: DEBUG
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MariaDBDialect
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sk045-teammate-secret
                  key: SPRING_DATASOURCE_PASSWORD
