apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk045-teammate
  namespace: skala-practice
  labels:
    app: sk045-teammate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk045-teammate
  template:
    metadata:
      labels:
        app: sk045-teammate
    spec:
      containers:
        - name: cursor-k8s-cluster-repo
          image: 514090833954.dkr.ecr.ap-southeast-1.amazonaws.com/cursor-k8s-cluster-repo:4ae5e514fbf76e67ff01c856f0d448e7d232cac4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
          # ConfigMap의 모든 데이터를 환경 변수로 가져옵니다.
          envFrom:
            - configMapRef:
                name: sk045-teammate-config
          # 개별 환경 변수를 설정합니다. (envFrom과 동일한 레벨)
          env:
            - name: USER_NAME
              value: sk045
            - name: LOGGING_LEVEL_ROOT
              value: DEBUG
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MariaDBDialect
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sk045-teammate-secret
                  key: SPRING_DATASOURCE_PASSWORD
